---
- hosts: "{{ hosts_prompt }}"
  gather_facts: yes
  vars_prompt:
     - name: "hosts_prompt" ## Host where playbook about to play
       prompt: "Enter the Host or Host group need to run with this Playbook Eg.172.19.6.xx"
       private: no
     - name: "vm_name"
       prompt: "Enter the VM Name"
       private: no
     - name: "password_prompt" ## New Password
       prompt: "Enter the New Password to Change"
       private: yes
  tasks:
    - name: Please Re-Enter password!
      command: python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
      register: new_password
      delegate_to: localhost
    - debug:
       msg: "{{ new_password }}"
    - name: Update Root user's Password
      user:
         name: root
         update_password: always
         password: "{{ new_password.stdout }}"
      when: ansible_distribution == 'CentOS'
    - name: Insert/Update VM report at the start of the file
      blockinfile:
        path: /root/ProjectK/{{ vm_name }}.txt
        marker: "{mark}New Customer VM Details"
        insertbefore: BOF
        marker_begin: "*Written by 伟明.ANA*"
        marker_end: "Please Delete this"
        block: |
            Time Activated = {{ ansible_date_time.date }} {{ ansible_date_time.time }} {{ ansible_date_time.weekday }}
            OS Distribution = {{ ansible_distribution }} {{ ansible_distribution_version }}
            CPU = {{ ansible_processor_vcpus }} Core
            Memory = {{ ansible_memtotal_mb }} MB
            Storage = {{ ansible_lvm['vgs']['centos_lvmtest']['size_g']}} GB
            User = root
            Password = {{ password_prompt }}
      delegate_to: localhost
      when: ansible_distribution == 'CentOS'
      
    - name: Remove marker_end line
      lineinfile:
         path: /root/ProjectK/{{ vm_name }}.txt
         state: absent
         regexp: '^Please'
    - name: run python script to send report to skype group chats
      shell: /bin/echo -e "ProjectK/{{ vm_name }}.txt" | python /root/PythonCodes/Send2Skype.py
      tags: script
      delegate_to: localhost
